[env]
SIMULATOR_IMAGE="ghcr.io/delta/codecharacter-simulator:latest"
CPP_COMPILER_IMAGE="ghcr.io/delta/codecharacter-cpp-compiler:latest"
CPP_RUNNER_IMAGE="ghcr.io/delta/codecharacter-cpp-runner:latest"
JAVA_COMPILER_IMAGE="ghcr.io/delta/codecharacter-java-compiler:latest"
JAVA_RUNNER_IMAGE="ghcr.io/delta/codecharacter-java-runner:latest"
PYTHON_RUNNER_IMAGE="ghcr.io/delta/codecharacter-python-runner:latest"

MAX_LOG_SIZE="200000"
COMPILATION_TIME_LIMIT="5"
RUNTIME_TIME_LIMIT="10"
COMPILATION_MEMORY_LIMIT="300m"
RUNTIME_MEMORY_LIMIT="100m"
EPOLL_WAIT_TIMEOUT="30000"

RABBITMQ_HOST="localhost"
RABBITMQ_USERNAME="guest"
RABBITMQ_PASSWORD="guest"
REQUEST_QUEUE="gameRequestQueue"
PVP_REQUEST_QUEUE="gamePvpRequestQueue"
RESPONSE_QUEUE="gameStatusUpdateQueue"

MAP_SIZE="64"
